spring:
  application:
    name: spring-rest-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_rest_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  data:
    dir: ./data
  upload:
    base-dir: "./upload"              # 프로젝트루트/upload
    public-base-url: "http://localhost:8080/upload"
